name: Salvar Novo Usuario no Banco

on:
  repository_dispatch:
    types: [novo_cadastro]

jobs:
  atualizar_banco:
    runs-on: ubuntu-latest
    steps:
      - name: Baixar codigo do repositorio
        uses: actions/checkout@v4

      - name: Adicionar dados no arquivo JSON
        run: |
          PAYLOAD='${{ toJson(github.event.client_payload) }}'
          if [ ! -f banco_dados/usuarios.json ]; then
            mkdir -p banco_dados
            echo "[]" > banco_dados/usuarios.json
          fi
          python3 -c "import json; f=open('banco_dados/usuarios.json','r'); dados=json.load(f); f.close(); novo=json.loads('''$PAYLOAD'''); dados.append(novo); f=open('banco_dados/usuarios.json','w'); json.dump(dados,f,indent=2); f.close()"

      - name: Gravar alteracoes no banco do GitHub
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add banco_dados/usuarios.json
          git commit -m "Banco atualizado: Novo usuario cadastrado"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
